apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
spec:
  selector:
    matchLabels:
      app: cloudflare-ddns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      containers:
        - image: ghcr.io/balazshorvath/cloudflare-ddns:latest
          name: cloudflare-ddns
